server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankx
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
    h2:
      console:
        enabled: true
        path: /h2
management:
  endpoints:
    web:
      exposure:
        include: health,metrics

resilience4j:
  circuitbreaker:
    instances:
      riskClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      riskClient:
        maxAttempts: 3
        waitDuration: 200ms
  timelimiter:
    instances:
      riskClient:
        timeoutDuration: 1s
logging:
  level:
    org.springframework.r2dbc: warn
    org.springframework.data.mongodb: info
    org.hibernate.SQL: debug